### ISSUE TITLE
Get rid of flaky tests

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/community#369] opened 2019-09-30 06:32 UTC
Created on 2019-09-30 by Piotr Bochynski (@pbochynski ).

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Get rid of flaky tests |
| Due date | 2019-10-06  |
| Status | Accepted on 2019-10-06 |
| Decision type | Binary |
| Affected decisions | None|

## Decision

Test that fails or passes without code change is categorized as flaky. Let's start with the tests that fail at least once on a nightly cluster (upgrade, backup & restore tests are excluded from this proposal). Having such tests in the CI pipeline that runs for hours blocks the development. The more strict process is required to remove flaky tests from Kyma code base. The decision is to put all the flaky tests in the quarantined area. The person who spotted flaky tests should:
- create a pull request that ignores the test
- create the issue for fixing the test with the following labels: test-missing, test-failing, critical
- notify code-owners of failing tests issue 
- notify one of the repository admins about the pull request to immediately remove the test from master (merge)

The person who wants to reintroduce test from quarantine has to:
- prove that the test passed without any retries on the next 3 runs on Minikube and GKE cluster

## Consequences

The quarantined tests are decreasing code coverage and block the release. The release process has to be updated in the way that all missing tests are fixed or the use cases they cover are tested manually on the release candidate. It means that it can influence the release timeline if there are many manual tests to execute. Kyma team should also prioritize fixing flaky tests before any features (critical label).

**Comment by michal-hudy** [comment] 2019-09-30 06:37
Generally, I agree with the proposed solution. One thing is missing - the requirements that the test must meet to be re-enabled.

**Comment by pbochynski** [comment] 2019-09-30 06:46
I added the section about reintroducing tests from quarantine.

**Comment by aszecowka** [comment] 2019-09-30 07:07
1. Can we say that everyone can report flaky test, but on-call person from CI-Force team has a duty of reporting such issues happening on post-master jobs?
 
2. The person reporting flaky test should also modify the release process document, that given functionality has to be covered by manual tests.

**Comment by mszostok** [comment] 2019-09-30 07:51
I totally agree, but IMO such an approach can lead to some functional regression. IMO Kyma people are not always focused on having well-tested functionality. Together with such proposition, we should develop our culture about having such routine like

1. Creating functionality
2. Writing stable tests 
3. If test turn out to be flaky then disable it
4. **and in the same time starts working on enabling that**

e.g. There should be a statement that once a week dashboard with `test/failing` label is reviewed with the strict restriction that each issue should be fixed (or at least started work) max in a few days. 

Because I'm a little bit scared that this proposal will evolve from `Get rid of flaky tests` to `Get rid of tests`, but maybe it's my imaginary fears

**Comment by pbochynski** [comment] 2019-09-30 08:20
@aszecowka @mszostok I think I covered your comments in the consequences section. It is clear that all those cases create a **critical** issue (which is first to fix), and the release process already covers the cases for **test-missing**.
If you want to add some sentence just write it down - I will edit the issue :)
I didn't want to make it too long.

**Comment by derberg** [comment] 2019-10-02 09:59
Please make it clear that flaky test is a test that failed at least once on a stability cluster.
Please extend consequences with clear information that more manual tests mean longer release process because of manual testing of the release candidates

**Comment by sayanh** [comment] 2019-10-02 10:01
@pbochynski 
> Test that fails or passes without code change is categorized as flaky.
I think we should have the criteria here to consider a test flaky and disable it.

Maybe this is far-fetched for now. How about complex scenarios that are flaky as well? E.g. upgrade or backup/restore tests It is single go binary where all the tests are baked in. We need to think through the way how can we mark that one flaky and re-enable it later? By the way, the stability checker just runs `testing.sh` for now IIRC.

**Comment by pbochynski** [comment] 2019-10-02 11:13
Thanks @derberg and @sayanh. I updated the description with your suggestions.

**Comment by derberg** [comment] 2019-10-02 11:49
@pbochynski sorry, second thought, stability cluster is not the best choice as it is built once a week afaik, so we should rather monitor this on nightly to react on changes quicker

**Comment by pbochynski** [comment] 2019-10-02 12:24
@derberg done :)

**Comment by pbochynski** [comment] 2019-10-07 06:25
We reached a consensus. I am closing the issue with status: **approved**.

**Comment by derberg** [comment] 2019-10-10 14:33
@Disper 
* We discussed it in detail when we talked about this proposal and that was pretty obvious that this will be harsh start with many commented out issues. It was also clear that these critical issues created as an outcome of disabled tests are priority 1 over features
* Nobody should test manually on release, but just make sure tests can be enabled again. If someone decides to not fix tests and just do manual testing, I suggest do manual tests on each PR. I guess better to fix tests first then
* What logs from what tests are actually missing? please provide an example. This should not be the case. Take a look on below screenshot, there are logs from the day when tests were failing and the decision was made to disable them
![image (8)](https://user-images.githubusercontent.com/6995927/66578442-659fff80-eb7b-11e9-87ef-2c544f8fab47.png)

**Comment by mszostok** [comment] 2019-10-10 18:05
@Disper 
Additionally, there is new AC that each team should provide a way for disabling only a particular test instead of disabling the whole suite for a given domain, see: https://github.com/kyma-project/kyma/issues/5919#issuecomment-540470238 

What's more, all team should take issues with a disabled test as standard critical issues - it means immediate investigation/fixes before further features development

**Comment by mszostok** [comment] 2019-10-10 18:13
the most problematic part is why we still have **10** issues in TODO column, why no one is working on that?

<img width="751" alt="Screen Shot 2019-10-10 at 20 10 23" src="https://user-images.githubusercontent.com/17568639/66594797-19b08300-eb9a-11e9-8e84-0f0e734f5e19.png">

at least someone should take issue and prepare PR to disable only the sub-test which is failing and re-enable rest test for a given domain, but with a new AC, he should also provide a way for CI on-call person ability to disable only particular test in the future.

**Comment by Disper** [comment] 2019-10-11 05:59
@derberg my concern is that new changes are being introduced and so far and I 100% agree that manually testing shouldn't be done just on the release. The thing is, that at the moment, with having **more than 50% tests** disabled we shouldn't merge anything unless we test manually for each missing tests. Of all teams.

Otherwise we are not compliant with functional correctness of our Product Standards.

@lilitgh could you check @derberg comment if it helps? 

> Let's start to be really responsible for our tests.
@mszostok well said! 

Disabling a single test instead of a full suite would be a way to go. @mszostok Could you point me to a place where it was done and works? I had an information that it's impossible due to our tests naming inconsistencies and maybe we're missing some knowledge here.

**Comment by sjanota** [comment] 2019-10-11 06:43
@derberg @mszostok I have to disagree with your perception of criticality. Two reasons:
1. As you both said, the team is able to decide which work will be done next. They should take the criticality of the issue into account but still, it is their decision. They may found that there is something more important or the fixing takes more time than expected. 
2. Our system has a lot of internal dependencies. A change in one place may break completely different parts of the system. To really follow the "no development until tests are fixed" rule we would need to completely follow lean and hold the whole line. No team is working if any test is broken/disabled. Integration tests are not the team's tests. They all are e2e tests as they test the whole cluster. 

IMO our current situation shows that the problem is not with particular tests, but with a way how we test. Maybe it's infrastructure, system architecture, test strategy, I don't know. I just doubt that all of us are so poor engineers that we cannot get our tests done right.

I think that the way to go right now should be to stop and think, not blindly "just do something". We tried that (I was also a fan of this idea) and it didn't work. We should have a group of people from different teams **working together on high priority**, to find the cause and suggest the course of action. Call it WG if you like, I just want to see someone actually thinking about the problem instead.

**Comment by mareknawa** [comment] 2019-10-11 06:54
Durinng yesterday's SoS meeting we decided to reopen this issue. We have more than 60% of all tests suites disabled after 4 days. We don't have a mechanism to disable single tests at the moment and with current approach we loose too many good test cases.
Urgent improvement is necessary.
Please, comment under this issue what we've learned during last few days and what needs to be improved.

**Comment by derberg** [comment] 2019-10-11 08:31
This is a decision that was done basing on detailed discussions and after agreeing what is the consequence. You should not reopen this ticket, but instead, prepare a new decision proposal so all interested maintainers can discuss the idea. In new proposal link to this one

**Closed by derberg** 2019-10-11 08:31 UTC
Labels: area/quality, decision
